### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Result: Unexpected function code in answer

### ISSUE THREAD

**Issue by Jatich** [s7connector/s7connector#103]
Caused by: java.lang.IllegalArgumentException: Result: Unexpected function code in answer

**Comment by shixingze** [comment]
一样求解决

**Comment by aboluo-gy** [comment]
Interface.write: java.net.SocketException: Connection reset by peer: socket write error
Exception in thread "main" com.github.s7connector.exception.S7Exception: dispense dbnum(0) byteoffset(10) blocksize(1)
	at com.persagy.s7.impl.S7SerializerImpl.dispense(S7SerializerImpl.java:251)
	at com.persagy.s7.util.PlainTutorialExample.read(PlainTutorialExample.java:68)
	at com.persagy.s7.util.PlainTutorialExample.testRead(PlainTutorialExample.java:62)
	at com.persagy.s7.util.PlainTutorialExample.main(PlainTutorialExample.java:90)
Caused by: java.lang.IllegalArgumentException: Result: Unexpected function code in answer
	at com.github.s7connector.impl.S7BaseConnection.checkResult(S7BaseConnection.java:55)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:101)
	at com.persagy.s7.impl.S7SerializerImpl.dispense(S7SerializerImpl.java:248)
	... 3 more
