### ISSUE TITLE
exception when last element of datablock is string

### ISSUE THREAD

**Issue by parich007** [s7connector/s7connector#52]
When I construct a datablock which has its last element of type string and attempt to read it via the serializer.dispense method I get the following exception: -

com.github.s7connector.exception.S7Exception: dispense
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:157)
	at com.ascari.s7.main$4.widgetSelected(main.java:225)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at com.ascari.s7.main.open(main.java:66)
	at com.ascari.s7.main.main(main.java:51)
Caused by: java.lang.IllegalArgumentException: Result: the desired address is beyond limit for this PLC
	at com.github.s7connector.impl.S7BaseConnection.checkResult(S7BaseConnection.java:55)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:101)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:93)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:93)
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:154)
	... 9 more

if I append the datablock with an additional non-string type, the read works successfully..

**Comment by thomasrudin** [comment]
Sounds like an issue with string-parsing, on what version are you?

**Comment by parich007** [comment]
I'm using Version 2.1

**Comment by thomasrudin** [comment]
Sounds like a bug in the size-prediction of the dispenser
I will investigate...

**Comment by thomasrudin** [comment]
hmm, i can't reproduce this :confused: 
Did you make sure that your datablock has enough size, for example:
```java
	@Datablock
	public static class MyDB {
		@S7Variable(type=S7Type.STRING, byteOffset=0, size=20)
		public String str;
	}
```
This DB should have at least 22 bytes (20 bytes string + 1 byte current length + 1 byte max length)
My guess is, that the dispenser tries to read over the end of the datablock...

**Comment by a13u** [comment]
@parich007 can you provide a concrete example: Snapshot from the db, annotations and your read/write code? Then I will test it!
