### ISSUE TITLE
Exception when Stype is DWORD

### ISSUE THREAD

**Issue by packo6300** [s7connector/s7connector#53]
I have a trouble, when try read a DWORD, the documentation say a DWORD is a long type java but when i try read with long data, give a exception, the only way to read DWORD is a int data type for java.

and when i try write data on int value the exception is the same.

**this work fine for read data:**

@S7Variable(byteOffset=278, type=S7Type.DWORD)
    public int tiempoDescanso;

**that make the exception:**

@S7Variable(byteOffset=278, type=S7Type.DWORD)
    public long tiempoDescanso;

com.github.s7connector.exception.S7Exception: dispense
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:145)
	at com.mycompany.mavenproject1.helper.PlcHelper.readPlc(PlcHelper.java:39)
	at com.mycompany.mavenproject1.principal.conecta(principal.java:281)
	at com.mycompany.mavenproject1.principal.jButton1ActionPerformed(principal.java:324)
	at com.mycompany.mavenproject1.principal.access$100(principal.java:21)
	at com.mycompany.mavenproject1.principal$2.actionPerformed(principal.java:86)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.github.s7connector.exception.S7Exception: extractBytes
	at com.github.s7connector.impl.serializer.S7SerializerImpl.extractBytes(S7SerializerImpl.java:78)
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:143)
	... 42 more
Caused by: java.lang.ClassCastException: Cannot cast java.lang.Integer to java.lang.Long
	at java.lang.Class.cast(Class.java:3369)
	at com.github.s7connector.impl.serializer.converter.LongConverter.extract(LongConverter.java:34)
	at com.github.s7connector.impl.serializer.S7SerializerImpl.extractBytes(S7SerializerImpl.ja

**Comment by thomasrudin** [comment]
Maybe related to #52

**Comment by thomasrudin** [comment]
This looks familiar with #42 but that got solved with 44d0f23cc885b8b18f8795026e38f690ed78fb5a
It should be included in version 2.1, what version are you using?
