### ISSUE TITLE
Unable to determine connection dropdown

### ISSUE THREAD

**Issue by mdurello** [s7connector/s7connector#55]
I'm trying to read data cyclically (every 500ms) from a Siemens PLC. In my code I create an instance of S7TCPConnector only once when I start the application, and I always use the same instance.
However, if the TCP connection is interrupted (simply by disconnecting the network cable from the PC), no exceptions are triggered when I call the read(..) method of S7Connect interface, and neither the S7Connect nor the S7TCPConnection class have any method available to verify that the TCP connection is still active. The read(..) method returns to me a bool[] with almost 0 filled,but it's impossible to discriminate if the input is valid or not.

Is it possible to make the read(..) method of the S7TCPConnection class throw an exception when it is called when the TCP connection is dead?

**Comment by thomasrudin** [comment]
Are you sure no exception gets thrown? I think the underlying Socket exception should be thrown back...
Anyways: that needs to be unit-tested somehow...

**Comment by thomasrudin** [comment]
ok, i'm unable to reproduce this with a unit-test, any chance you can tell me where in the code it "hangs"..

**Comment by mdurello** [comment]
I'll make a sample project with the reproduction of the problem ASAP.
Thank you.

**Comment by mdurello** [comment]
I can't reproduce the issue without a real S7 device to test on it. I can reproduce it only with a Siemens PLC, if i disconnect the ethernet cable.
However I did some test in debug mode, when I call the method `read(..)` from the `S7Connector`, I saw that in class `TCPConnection`, calling the method `exchange(..)`, in line 82 there is a call to the method `int readISOPacket()`, but the output is never used.
I saw that the integer returned by this method is 0 when i disconnect the cable (i suppose because there is no responce in the socket when I try to read something), a number > 0 otherwise.

If you see at the attached file:
[test.zip](https://github.com/s7connector/s7connector/files/2914692/test.zip)

I've included the Main class used in my tests and the output shown in the system console.
It's important to add that i've disconnected the cable between cycle 2 and cycle 3. Starting from cycle 3 you can see that the time for calling the method `read(..)` increase from ~ 1000ms to ~1900ms. This because inside `read(..)` method call there is a call to the method `read(..)` of the class `PLCInterface` that makes 500 iteration to retry the read that cause failure. In the system output you can see that the soket is closed only about 20 seconds after disconnecting the cable, but the `read(..)` method never throws any exceptions, even when the soket is closed.
If you want some other details I can provide you some additional informations.

**Comment by a13u** [comment]
I have the same issue!
@mdurello  which PLC are you using?

**Comment by a13u** [comment]
moved from #73 
I have a similar problem. I am using a `ET200 SP ` CPU and I use S7connector via maven:
```
		<dependency>
			<groupId>com.github.s7connector</groupId>
			<artifactId>s7connector</artifactId>
			<version>2.1</version>
		</dependency>
```

I can connect and read/write datablocks using the annotation approach. So the communication works fine! Now, I am testing some exceptional cases. Surprisingly, when I unplug the network cable after a connection has been established my serializer does not throw an exception when executing a dispense operation
`serializer.dispense(this.type, this.getDbnum(), this.getOffset());`
The only thing that I get is the following message on the output line:

> Interface.write: java.net.SocketException: Connection reset by peer: socket write error

I do not get an error stack trace...

However, the dispense does NOT throw an error. It seems like an exception is caught in the S7 connector? Wouldn't it be better if an error is thrown so that I can do re-connect try? How can I identify problems with my connection? Is there something like `serializer.isconnected()`

**Comment by a13u** [comment]
With S7-1200:

```
Interface.write: java.net.SocketException: Connection reset by peer: socket write error
Exception in thread "Thread-2683" Interface.write: java.net.SocketException: Connection reset by peer: socket write error
com.github.s7connector.exception.S7Exception: dispense
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:157)
..
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 35 out of bounds for byte[12]
	at java.base/java.lang.System.arraycopy(Native Method)
	at com.github.s7connector.impl.nodave.S7Connection.readBytes(S7Connection.java:325)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:99)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:93)
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:154)
	... 3 more
```

With S7-1500: no exception

**Comment by mdurello** [comment]
> I have the same issue! I get no exception, only an error message:
> `Interface.write: java.net.SocketException: Connection reset by peer: socket write error`
> Further, I also recognized that the reading time increases dramatically if I unplug the cable...
> @mdurello which PLC are you using? Have you solved the issue?
> 
> As far as I remember I got an exception when using a S7-1200 but I do not get an exception when using a S7-1500 (ET200 SP) --> I will try it in the next days...

I'm using an S7-1500.

**Comment by a13u** [comment]
So that's the issue - on S7-1200 it works!

**Comment by Michanord** [comment]
I also have the same issue. I am pretty much doing the same as the initial poster.
When restarting the PLC the connection is broken and I have no way to detect that in the code because only `Interface.write: java.net.SocketException: Connection reset by peer: socket write error` is printed on the console.
It seems like com.github.s7connector.impl.nodave.PLCinterface#write is the source of that print. 

With the current try-catch block the write method just hides every IOException. It would help me if the exception is just passed to the caller and not hidden.
