### ISSUE TITLE
Exception when reading Byte Array

### ISSUE THREAD

**Issue by a13u** [s7connector/s7connector#60]
I am working with the annotations of your project. Till now, I was reading and writing various types of variables and they worked fine. Now, I try to read an array. The datablock looks like the following

![arrayissue](https://user-images.githubusercontent.com/11412016/55806860-68913900-5ae1-11e9-8ec1-7455ecfae681.png)

I created a bean class with a variable:
```
	@S7Variable(type = S7Type.BYTE, byteOffset = 0, bitOffset = 0, arraySize = 100)
	public Byte[] ourField;
```

When I try to read the datablock I get the following error:
_the desired address is beyond limit for this plc_

When I remove the S7 array variables I do not get an error, so I assume that the errors are resulting from the array variables (reading the boolean Variables works fine!). 
I know this [issue](https://github.com/s7connector/s7connector/issues/44) but here the issue seems to be solved by using Byte instead of byte - this does not work for me (I tried both).

The PLC I am using is a S1200 and I am working with TIA portal V15

**Comment by thomasrudin** [comment]
It looks like the connector tries to read from an address out of range of the PLC.

Can you share the following:
* How do you connect to the PLC (code snippet)?
* How do you read/write to the PLC (code snippet)?

If possible:
* The debug output

**Comment by a13u** [comment]
yes, sure:

Connection to SPS:

```
		connector = S7ConnectorFactory.buildTCPConnector().withHost(SPS_IP).withRack(0) // optional
				.withSlot(1) // optional
				.build();
		serializer= S7SerializerFactory.buildSerializer(connector);
```

```
public class RFIDReaderBean {
@S7Variable(byteOffset=0, bitOffset=0, type=S7Type.BYTE, arraySize=10)
public Byte[] read0;
}
```
The serialization:
`serializer.dispense(RFIDReaderBean.class , 4, 0)`

The error
```
Exception in thread "main" com.github.s7connector.exception.S7Exception: dispense
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:157)
	at fancyfactory.robotstation.data.datablockhandler.RFIDReaderBeanDatablockHandler.readDatablock(DatablockHandler.java:22)
	at stationtest.TestLauncher.main(TestLauncher.java:22)
Caused by: java.lang.IllegalArgumentException: Result: the desired address is beyond limit for this PLC
	at com.github.s7connector.impl.S7BaseConnection.checkResult(S7BaseConnection.java:55)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:101)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:93)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:93)
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:154)
	... 16 more
```

For boolean Variables my code works!

**Comment by a13u** [comment]
Do you need any further information?

**Comment by thomasrudin** [comment]
No, thanks.
I'm looking into reproducing that locally, maybe in a unit-test.
It will take a few days though... :smile:

**Comment by thomasrudin** [comment]
I played around with a unit test simulating your issue.
So far it looks like it requests the proper data from the PLC:

### Test case

Serializer request:
```java
 serializer.dispense(RFIDReaderBean.class , 4, 0) // 10 bytes data length (in RFIDReaderBean)
```

Actual request from the low-level api:
* Request to DB 4 at offset 0 with length=10

### Repro

Are you sure that the *direct* boolean requests work?
I expected that the low-level call should fail with the same error:
```
byte[] data = connector.read(DaveArea.DB, 4, 10, 0);
```

Can you confirm that the *direct* calls work and the *Serializer* calls don't work (with the same addresses)?

**Comment by a13u** [comment]
Thank you!
I will retry it!

Von meinem iPhone gesendet

**Comment by a13u** [comment]
I re-tried it with a simplified program. It works - when I found out why it did not work before then I will notify you. Thank you for your great support and sorry for this issue! Awesome library!!

**Comment by thomasrudin** [comment]
glad to hear that :smile:

**Comment by pyctt** [comment]
I want to know why
`com.github.s7connector.exception.S7Exception: dispense
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:157)
	at com.example.e_management.service.impl.PLCConnectionImpl.lambda$null$0(PLCConnectionImpl.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.github.s7connector.impl.nodave.S7Connection.readBytes(S7Connection.java:325)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:99)
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:154)
	... 8 more`
